### ISSUE TITLE
Can't load votes from 2014-11-27

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#106]
Trying to reload all votes after the recent change isn't working:

```
henare@mana:~/Documents/projects/openaustralia/code/ukraine/publicwhip rvm:(ruby-2.0.0-p353) git:(develop)$ bundle exec rake application:load:ukraine:people application:load:ukraine:vote_events[2014-11-27,2015-11-18] application:cache:all
Loading Ukraine Popolo data from https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/data/Ukraine/Verkhovna_Rada/ep-popolo-v1.0.json...
Loading 441 people...
Loading 532 memberships...
Loading Ukraine Popolo data from https://arcane-mountain-8284.herokuapp.com/vote_events/2014-11-27...
Loading Ukraine Popolo data from https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/data/Ukraine/Verkhovna_Rada/ep-popolo-v1.0.json...
Loading 7 vote_events...
Loading 418 votes...
rake aborted!
ActiveRecord::RecordNotFound: ActiveRecord::RecordNotFound
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.12/lib/active_record/relation/finder_methods.rb:104:in `take!'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.12/lib/active_record/relation/finder_methods.rb:87:in `find_by!'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.12/lib/active_record/querying.rb:7:in `find_by!'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/data_loader/ukraine/vote_events.rb:39:in `block (3 levels) in load!'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/data_loader/ukraine/vote_events.rb:36:in `each'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/data_loader/ukraine/vote_events.rb:36:in `block (2 levels) in load!'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/data_loader/ukraine/vote_events.rb:19:in `block in load!'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/data_loader/ukraine/vote_events.rb:18:in `each'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/data_loader/ukraine/vote_events.rb:18:in `load!'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/tasks/ukraine.rake:21:in `block (5 levels) in <top (required)>'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.12/lib/active_support/core_ext/range/each.rb:7:in `each'
/home/henare/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.1.12/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
/home/henare/Documents/projects/openaustralia/code/ukraine/publicwhip/lib/tasks/ukraine.rake:20:in `block (4 levels) in <top (required)>'
/home/henare/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/home/henare/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => application:load:ukraine:vote_events
(See full trace by running task with --trace)
henare@mana:~/Documents/projects/openaustralia/code/ukraine/publicwhip rvm:(ruby-2.0.0-p353) git:(develop)$ 
```

**Comment by henare** [comment]
Once this is fixed, don't forget to do a full reload of production.

**Comment by henare** [comment]
It's because for the first 3 votes of the parliament everyone is listed as an independent:

http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=20
http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=21
http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=22
